# Generated by Django 5.2.15 on 2026-07-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_stage', models.CharField(choices=[('PENDING', 'PENDING'), ('OCR', 'OCR'), ('INTELLIGENCE', 'INTELLIGENCE'), ('ORGANIZATION', 'ORGANIZATION'), ('EMBEDDING', 'EMBEDDING'), ('ASSISTANT', 'ASSISTANT'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=50)),
                ('processing_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_pages', models.JSONField(blank=True, default=list)),
                ('extracted_metadata', models.JSONField(blank=True, default=dict)),
                ('embeddings_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Intelligence',
                'verbose_name_plural': 'Document Intelligence',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PENDING', 'PENDING'), ('OCR', 'OCR'), ('INTELLIGENCE', 'INTELLIGENCE'), ('ORGANIZATION', 'ORGANIZATION'), ('EMBEDDING', 'EMBEDDING'), ('ASSISTANT', 'ASSISTANT'), ('COMPLETED', 'COMPLETED')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('message', models.TextField()),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
